{{- if and (or .Values.backup.litestream.enabled .Values.backup.objectMirror.enabled) .Values.backup.external.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drust.labels" . | nindent 4 }}
type: Opaque
stringData:
  backup-s3-access-key: {{ required "backup.external.accessKey required when a backup feature is enabled and backup.external.create=true" .Values.backup.external.accessKey | quote }}
  backup-s3-secret-key: {{ required "backup.external.secretKey required when a backup feature is enabled and backup.external.create=true" .Values.backup.external.secretKey | quote }}
{{- end }}
