//! v1.27 golden-file tests. The fixture files in tests/codegen/golden/
//! are regenerated by running:
//!
//!     DRUST_CODEGEN_REGENERATE=1 cargo test --test codegen_golden
//!
//! Without that env var the test compares renderer output to the
//! checked-in fixture.

use drust::codegen::{render_openapi_for_test, render_typescript_for_test, render_zod_for_test};

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/codegen/golden").join(name)
}

fn check_or_regen(actual: &str, file: &str) {
    let path = fixture_path(file);
    if std::env::var("DRUST_CODEGEN_REGENERATE").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, actual).unwrap();
        println!("regenerated {}", path.display());
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    if expected != actual {
        let actual_path = path.with_extension(format!("actual.{}", path.extension().and_then(|s| s.to_str()).unwrap_or("")));
        std::fs::write(&actual_path, actual).unwrap();
        panic!("{} drift — diff {} vs {}", file, actual_path.display(), path.display());
    }
}

#[test]
fn openapi_matches_golden() {
    let json = render_openapi_for_test();
    let s = serde_json::to_string_pretty(&json).unwrap() + "\n";
    check_or_regen(&s, "openapi.json");
}

#[test]
fn typescript_matches_golden() {
    let s = render_typescript_for_test();
    check_or_regen(&s, "types.ts");
}

#[test]
fn zod_matches_golden() {
    let s = render_zod_for_test();
    check_or_regen(&s, "zod.ts");
}
