// Generated by drust v1.27 for tenant demo
// Do not edit by hand. Re-fetch from https://example.com/drust/t/demo/types.ts to refresh.
// Schema source: service

export type FilterAst =
  | { op: 'eq' | 'neq' | 'lt' | 'lte' | 'gt' | 'gte' | 'like' | 'in'; field: string; value: unknown }
  | { op: 'and' | 'or'; filters: FilterAst[] }
  | { op: 'not'; filter: FilterAst };

/** Blog posts */
export interface Posts {
  id: number;
  title: string;
  /** Markdown body */
  body: string | null;
  /** FK → users */
  author_id: number;
  embedding: number[] | null;
  /** @min 1 @max 5 */
  rating: number | null;
  tier: 1 | 2 | 3 | null;
  status: "draft" | "published" | null;
  /** @maxLength 64 */
  slug: string | null;
}

export interface PostsInsert {
  title: string;
  /** Markdown body */
  body: string | null;
  /** FK → users */
  author_id: number;
  embedding: number[] | null;
  /** @min 1 @max 5 */
  rating: number | null;
  tier: 1 | 2 | 3 | null;
  status: "draft" | "published" | null;
  /** @maxLength 64 */
  slug: string | null;
}

export interface PostsUpdate {
  title?: string;
  /** Markdown body */
  body?: string | null;
  /** FK → users */
  author_id?: number;
  embedding?: number[] | null;
  /** @min 1 @max 5 */
  rating?: number | null;
  tier?: 1 | 2 | 3 | null;
  status?: "draft" | "published" | null;
  /** @maxLength 64 */
  slug?: string | null;
}

export interface Users {
  id: number;
  email: string;
}

export interface UsersInsert {
  email: string;
}

export interface UsersUpdate {
  email?: string;
}

