// Generated by drust v1.27 for tenant demo
// Do not edit by hand. Re-fetch from https://example.com/drust/t/demo/types.ts to refresh.
// Schema source: service

export type FilterScalar = string | number | boolean | null;
export type FilterOp =
  | { eq: FilterScalar } | { ne: FilterScalar }
  | { gt: FilterScalar } | { gte: FilterScalar }
  | { lt: FilterScalar } | { lte: FilterScalar }
  | { like: string }
  | { in: FilterScalar[] } | { nin: FilterScalar[] }
  | { is_null: boolean } | { is_not_null: boolean };
// A leaf names EXACTLY ONE field; a TS index signature cannot express that
// bound, so the runtime parser (not this type) enforces it — {} and multi-field
// objects type-check here but are rejected server-side.
export type FilterAst =
  | { and: FilterAst[] }
  | { or: FilterAst[] }
  | { not: FilterAst }
  | { [field: string]: FilterScalar | FilterOp };

/** Blog posts */
export interface Posts {
  id: number;
  title: string;
  /** Markdown body */
  body: string | null;
  /** FK → users */
  author_id: number;
  embedding: number[] | null;
  /** @min 1 @max 5 */
  rating: number | null;
  tier: 1 | 2 | 3 | null;
  status: "draft" | "published" | null;
  /** @maxLength 64 */
  slug: string | null;
}

export interface PostsInsert {
  title: string;
  /** Markdown body */
  body: string | null;
  /** FK → users */
  author_id: number;
  embedding: number[] | null;
  /** @min 1 @max 5 */
  rating: number | null;
  tier: 1 | 2 | 3 | null;
  status: "draft" | "published" | null;
  /** @maxLength 64 */
  slug: string | null;
}

export interface PostsUpdate {
  title?: string;
  /** Markdown body */
  body?: string | null;
  /** FK → users */
  author_id?: number;
  embedding?: number[] | null;
  /** @min 1 @max 5 */
  rating?: number | null;
  tier?: 1 | 2 | 3 | null;
  status?: "draft" | "published" | null;
  /** @maxLength 64 */
  slug?: string | null;
}

export interface Users {
  id: number;
  email: string;
}

export interface UsersInsert {
  email: string;
}

export interface UsersUpdate {
  email?: string;
}

