// Generated by drust v1.27 for tenant demo
// Re-fetch from https://example.com/drust/t/demo/zod.ts to refresh.
import { z } from 'zod';

export const FilterAstSchema: z.ZodType<unknown> = z.lazy(() =>
  z.union([
    z.object({ op: z.enum(['eq','neq','lt','lte','gt','gte','like','in']), field: z.string(), value: z.unknown() }),
    z.object({ op: z.enum(['and','or']), filters: z.array(FilterAstSchema) }),
    z.object({ op: z.literal('not'), filter: FilterAstSchema }),
  ])
);

export const PostsSchema = z.object({
  id: z.number().int(),
  title: z.string(),
  body: z.string().nullable(),
  author_id: z.number().int(),
  embedding: z.array(z.number()).length(1536).nullable(),
  rating: z.number().int().min(1).max(5).nullable(),
  status: z.enum(["draft", "published"]).nullable(),
  slug: z.string().max(64).nullable(),
});
export type Posts = z.infer<typeof PostsSchema>;

export const PostsInsertSchema = z.object({
  title: z.string(),
  body: z.string().nullable(),
  author_id: z.number().int(),
  embedding: z.array(z.number()).length(1536).nullable(),
  rating: z.number().int().min(1).max(5).nullable(),
  status: z.enum(["draft", "published"]).nullable(),
  slug: z.string().max(64).nullable(),
});
export type PostsInsert = z.infer<typeof PostsInsertSchema>;

export const PostsUpdateSchema = z.object({
  title: z.string().optional(),
  body: z.string().nullable().optional(),
  author_id: z.number().int().optional(),
  embedding: z.array(z.number()).length(1536).nullable().optional(),
  rating: z.number().int().min(1).max(5).nullable().optional(),
  status: z.enum(["draft", "published"]).nullable().optional(),
  slug: z.string().max(64).nullable().optional(),
});
export type PostsUpdate = z.infer<typeof PostsUpdateSchema>;

export const UsersSchema = z.object({
  id: z.number().int(),
  email: z.string(),
});
export type Users = z.infer<typeof UsersSchema>;

export const UsersInsertSchema = z.object({
  email: z.string(),
});
export type UsersInsert = z.infer<typeof UsersInsertSchema>;

export const UsersUpdateSchema = z.object({
  email: z.string().optional(),
});
export type UsersUpdate = z.infer<typeof UsersUpdateSchema>;

