// Generated by drust v1.27 for tenant demo
// Re-fetch from https://example.com/drust/t/demo/zod.ts to refresh.
import { z } from 'zod';

export const FilterScalarSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
export const FilterOpSchema = z.union([
  z.object({ eq: FilterScalarSchema }).strict(), z.object({ ne: FilterScalarSchema }).strict(),
  z.object({ gt: FilterScalarSchema }).strict(), z.object({ gte: FilterScalarSchema }).strict(),
  z.object({ lt: FilterScalarSchema }).strict(), z.object({ lte: FilterScalarSchema }).strict(),
  z.object({ like: z.string() }).strict(),
  z.object({ in: z.array(FilterScalarSchema) }).strict(), z.object({ nin: z.array(FilterScalarSchema) }).strict(),
  z.object({ is_null: z.boolean() }).strict(), z.object({ is_not_null: z.boolean() }).strict(),
]);
export const FilterAstSchema: z.ZodType<unknown> = z.lazy(() =>
  z.union([
    z.object({ and: z.array(FilterAstSchema) }),
    z.object({ or: z.array(FilterAstSchema) }),
    z.object({ not: FilterAstSchema }),
    z.record(z.union([FilterScalarSchema, FilterOpSchema]))
      .refine((o) => Object.keys(o).length === 1, { message: 'filter leaf must name exactly one field' }),
  ])
);

export const PostsSchema = z.object({
  id: z.number().int(),
  title: z.string(),
  body: z.string().nullable(),
  author_id: z.number().int(),
  embedding: z.array(z.number()).length(1536).nullable(),
  rating: z.number().int().min(1).max(5).nullable(),
  tier: z.union([z.literal(1), z.literal(2), z.literal(3)]).nullable(),
  status: z.enum(["draft", "published"]).nullable(),
  slug: z.string().max(64).nullable(),
});
export type Posts = z.infer<typeof PostsSchema>;

export const PostsInsertSchema = z.object({
  title: z.string(),
  body: z.string().nullable(),
  author_id: z.number().int(),
  embedding: z.array(z.number()).length(1536).nullable(),
  rating: z.number().int().min(1).max(5).nullable(),
  tier: z.union([z.literal(1), z.literal(2), z.literal(3)]).nullable(),
  status: z.enum(["draft", "published"]).nullable(),
  slug: z.string().max(64).nullable(),
});
export type PostsInsert = z.infer<typeof PostsInsertSchema>;

export const PostsUpdateSchema = z.object({
  title: z.string().optional(),
  body: z.string().nullable().optional(),
  author_id: z.number().int().optional(),
  embedding: z.array(z.number()).length(1536).nullable().optional(),
  rating: z.number().int().min(1).max(5).nullable().optional(),
  tier: z.union([z.literal(1), z.literal(2), z.literal(3)]).nullable().optional(),
  status: z.enum(["draft", "published"]).nullable().optional(),
  slug: z.string().max(64).nullable().optional(),
});
export type PostsUpdate = z.infer<typeof PostsUpdateSchema>;

export const UsersSchema = z.object({
  id: z.number().int(),
  email: z.string(),
});
export type Users = z.infer<typeof UsersSchema>;

export const UsersInsertSchema = z.object({
  email: z.string(),
});
export type UsersInsert = z.infer<typeof UsersInsertSchema>;

export const UsersUpdateSchema = z.object({
  email: z.string().optional(),
});
export type UsersUpdate = z.infer<typeof UsersUpdateSchema>;

