//! v1.27 — TypeScript renderer. Pure string templating; output is
//! byte-stable so golden-file diffs are useful.

use super::filter_ast_schema::FILTER_AST_TS;
use super::ir::{CodegenIr, CollectionIr, FieldIr, FieldType};
use std::fmt::Write;

pub fn render_typescript(ir: &CodegenIr) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by drust v1.27 for tenant {}",
        ir.tenant_id
    );
    let _ = writeln!(
        out,
        "// Do not edit by hand. Re-fetch from {}/t/{}/types.ts to refresh.",
        ir.base_url, ir.tenant_id
    );
    let _ = writeln!(
        out,
        "// Schema source: {}",
        if ir.include_descriptions {
            "service"
        } else {
            "anon"
        }
    );
    out.push('\n');
    out.push_str(FILTER_AST_TS);
    out.push('\n');
    for coll in &ir.collections {
        render_collection_block(&mut out, coll);
        out.push('\n');
    }
    out
}

fn render_collection_block(out: &mut String, coll: &CollectionIr) {
    let row = pascal(&coll.name);
    let insert = format!("{row}Insert");
    let update = format!("{row}Update");

    if let Some(d) = &coll.description {
        let _ = writeln!(out, "/** {} */", escape_jsdoc(d));
    }
    let _ = writeln!(out, "export interface {row} {{");
    for f in &coll.fields {
        render_field_line(
            out, f, /*all_optional*/ false, /*skip_server_managed*/ false,
        );
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "export interface {insert} {{");
    for f in &coll.fields {
        if f.server_managed {
            continue;
        }
        let optional = f.default.is_some();
        render_field_line(out, f, optional, false);
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "export interface {update} {{");
    for f in &coll.fields {
        if f.server_managed {
            continue;
        }
        render_field_line(out, f, /*all_optional*/ true, false);
    }
    out.push_str("}\n");
}

fn render_field_line(out: &mut String, f: &FieldIr, force_optional: bool, _skip_sm: bool) {
    let mut leading_doc = String::new();
    if let Some(fk) = &f.fk {
        let _ = writeln!(leading_doc, "  /** FK → {} */", fk);
    } else if let Some(d) = &f.description {
        let _ = writeln!(leading_doc, "  /** {} */", escape_jsdoc(d));
    }
    // v1.43 — numeric/length constraints surface as a JSDoc note (enum is
    // expressed structurally as a literal union below, so it needs no note).
    if let Some(note) = constraint_doc(f) {
        let _ = writeln!(leading_doc, "  /** {} */", escape_jsdoc(&note));
    }
    if !leading_doc.is_empty() {
        out.push_str(&leading_doc);
    }
    // v1.43 — an enum constraint renders as a string-literal union and
    // overrides the base TS type.
    let ts_ty = match f.constraints.as_ref().and_then(|c| c.enum_values.as_ref()) {
        Some(vals) => vals
            .iter()
            .map(|v| format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\"")))
            .collect::<Vec<_>>()
            .join(" | "),
        None => field_to_ts(&f.ty),
    };
    let null_suffix = if f.nullable { " | null" } else { "" };
    let opt_marker = if force_optional { "?" } else { "" };
    let _ = writeln!(out, "  {}{}: {}{};", f.name, opt_marker, ts_ty, null_suffix);
}

/// Build a `@min`/`@max`/`@maxLength` JSDoc note for the numeric/length
/// constraints, or `None` when the field has none of them.
fn constraint_doc(f: &FieldIr) -> Option<String> {
    let c = f.constraints.as_ref()?;
    let mut parts: Vec<String> = Vec::new();
    if let Some(min) = c.min {
        parts.push(format!("@min {}", ts_num(min)));
    }
    if let Some(max) = c.max {
        parts.push(format!("@max {}", ts_num(max)));
    }
    if let Some(len) = c.max_length {
        parts.push(format!("@maxLength {len}"));
    }
    if parts.is_empty() {
        None
    } else {
        Some(parts.join(" "))
    }
}

fn ts_num(n: f64) -> String {
    if n.fract() == 0.0 && n.is_finite() {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

fn field_to_ts(t: &FieldType) -> String {
    match t {
        FieldType::Text => "string".into(),
        FieldType::Integer => "number".into(),
        FieldType::Real => "number".into(),
        FieldType::Blob => "Uint8Array".into(),
        FieldType::Json => "unknown".into(),
        FieldType::Boolean => "boolean".into(),
        FieldType::Vector { .. } => "number[]".into(),
    }
}

fn pascal(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            chars
                .next()
                .map(|c| c.to_ascii_uppercase())
                .into_iter()
                .chain(chars)
                .collect::<String>()
        })
        .collect()
}

fn escape_jsdoc(s: &str) -> String {
    s.replace("*/", "*\\/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::ir::{CodegenIr, CollectionIr, FieldIr, FieldType};

    fn synth_ir() -> CodegenIr {
        CodegenIr {
            tenant_id: "test".into(),
            base_url: "http://localhost".into(),
            include_descriptions: true,
            collections: vec![CollectionIr {
                name: "posts".into(),
                description: Some("Blog posts".into()),
                fields: vec![
                    FieldIr {
                        name: "id".into(),
                        ty: FieldType::Integer,
                        nullable: false,
                        default: None,
                        fk: None,
                        description: None,
                        server_managed: true,
                        constraints: None,
                    },
                    FieldIr {
                        name: "title".into(),
                        ty: FieldType::Text,
                        nullable: false,
                        default: None,
                        fk: None,
                        description: None,
                        server_managed: false,
                        constraints: None,
                    },
                ],
                indexes: vec![],
                owner_field: None,
                realtime_enabled: false,
                has_vector: false,
            }],
        }
    }

    #[test]
    fn row_interface_includes_id() {
        let s = render_typescript(&synth_ir());
        assert!(s.contains("export interface Posts {"));
        assert!(s.contains("id: number;"));
        assert!(s.contains("title: string;"));
    }

    #[test]
    fn insert_omits_server_managed() {
        let s = render_typescript(&synth_ir());
        let insert_block = s
            .split("PostsInsert")
            .nth(1)
            .unwrap()
            .split("Posts")
            .next()
            .unwrap();
        assert!(
            !insert_block.contains("id:"),
            "id should not be in insert block"
        );
    }
}
