//! v1.27 — Zod renderer. Mirrors the TypeScript renderer's shape with
//! z.* constructors.

use super::ir::{CodegenIr, CollectionIr, FieldIr, FieldType};
use super::filter_ast_schema::FILTER_AST_ZOD;
use std::fmt::Write;

pub fn render_zod(ir: &CodegenIr) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by drust v1.27 for tenant {}", ir.tenant_id);
    let _ = writeln!(out, "// Re-fetch from {}/t/{}/zod.ts to refresh.", ir.base_url, ir.tenant_id);
    out.push_str("import { z } from 'zod';\n\n");
    out.push_str(FILTER_AST_ZOD);
    out.push('\n');
    for coll in &ir.collections {
        render_collection(&mut out, coll);
        out.push('\n');
    }
    out
}

fn render_collection(out: &mut String, coll: &CollectionIr) {
    let row = pascal(&coll.name);
    let _ = writeln!(out, "export const {row}Schema = z.object({{", row=row);
    for f in &coll.fields {
        render_field(out, f, /*optional*/ false);
    }
    out.push_str("});\n");
    let _ = writeln!(out, "export type {row} = z.infer<typeof {row}Schema>;", row=row);
    out.push('\n');

    let _ = writeln!(out, "export const {row}InsertSchema = z.object({{", row=row);
    for f in &coll.fields {
        if f.server_managed { continue; }
        let opt = f.default.is_some();
        render_field(out, f, opt);
    }
    out.push_str("});\n");
    let _ = writeln!(out, "export type {row}Insert = z.infer<typeof {row}InsertSchema>;", row=row);
    out.push('\n');

    let _ = writeln!(out, "export const {row}UpdateSchema = z.object({{", row=row);
    for f in &coll.fields {
        if f.server_managed { continue; }
        render_field(out, f, true);
    }
    out.push_str("});\n");
    let _ = writeln!(out, "export type {row}Update = z.infer<typeof {row}UpdateSchema>;", row=row);
}

fn render_field(out: &mut String, f: &FieldIr, force_optional: bool) {
    let mut s = field_to_zod(&f.ty);
    if f.nullable { s.push_str(".nullable()"); }
    if force_optional { s.push_str(".optional()"); }
    let _ = writeln!(out, "  {}: {},", f.name, s);
}

fn field_to_zod(t: &FieldType) -> String {
    match t {
        FieldType::Text => "z.string()".into(),
        FieldType::Integer => "z.number().int()".into(),
        FieldType::Real => "z.number()".into(),
        FieldType::Blob => "z.instanceof(Uint8Array)".into(),
        FieldType::Json => "z.unknown()".into(),
        FieldType::Boolean => "z.boolean()".into(),
        FieldType::Vector { dim } => format!("z.array(z.number()).length({dim})"),
    }
}

fn pascal(s: &str) -> String {
    s.split('_').filter(|p| !p.is_empty()).map(|p| {
        let mut chars = p.chars();
        chars.next().map(|c| c.to_ascii_uppercase()).into_iter().chain(chars).collect::<String>()
    }).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::ir::{CodegenIr, CollectionIr, FieldIr, FieldType};

    #[test]
    fn vector_field_emits_length_call() {
        let ir = CodegenIr {
            tenant_id: "t".into(), base_url: "x".into(), include_descriptions: false,
            collections: vec![CollectionIr {
                name: "docs".into(), description: None, fields: vec![FieldIr {
                    name: "emb".into(), ty: FieldType::Vector { dim: 768 },
                    nullable: false, default: None, fk: None, description: None, server_managed: false,
                }], indexes: vec![], owner_field: None, realtime_enabled: false, has_vector: true,
            }],
        };
        let s = render_zod(&ir);
        assert!(s.contains("z.array(z.number()).length(768)"));
    }
}
